### ISSUE TITLE
404 for the new container address

### ISSUE THREAD

**Issue by alaq** [josh/imdb-trakt-sync#13]
I get a 404 error when trying to access https://ghcr.io/josh/imdb-trakt-sync
Am I missing something?

I get redirected to https://github.com/-/josh/packages/container/package/imdb-trakt-sync which is also 404

I also can't pull the image, even while logged in to ghcr.io

> Pulling imdb_trakt_sync (ghcr.io/josh/imdb-trakt-sync:)...
ERROR: pull access denied for ghcr.io/josh/imdb-trakt-sync, repository does not exist or may require 'docker login': denied: permission_denied: read_package

**Comment by josh** [comment]
D'oh, looks like new GHCR images are private by default. Public now! Thanks!
