### ISSUE TITLE
Run on start

### ISSUE THREAD

**Issue by 2fst4u** [josh/imdb-trakt-sync#22]
Rather than setting an interval, is it possible to have the script just run when it starts?

For context, I run kubernetes and Iike to use the kubernetes cronjob feature to run scripts like this so they start, run, and then completely break down once complete. This way host resources are saved for scheduling.

This could be done via an environment variable potentially.

**Comment by josh** [comment]
If you just omit `TICKERD_INTERVAL` it will just run the sync script once and exit. The [tickerd scheduler I’m using has a few other options for scheduling based on cron syntax and intervals](https://github.com/josh/tickerd/blob/main/main.go#L54-L56). All of which can be configured with environment variables. I hope that helps!
