### ISSUE TITLE
README Update Request 

### ISSUE THREAD

**Issue by Valkryst** [josh/imdb-trakt-sync#24]
1. Could you verify the steps provided in the README?
2. Could you add additional information on installation/setup?
3. Could you add additional information on common (if any) errors and how to debug them?

I was unable to locate the correct value to use as the `TRAKT_ACCESS_TOKEN` environment variable through their site. I had to resort to [this](https://reqbin.com/veotsc62) random website to pull the token for me.

Also, some users may be unaware of Docker and how it works. A link to their installation instructions and launch commands may help others.

**Comment by josh** [comment]
Maybe checkout https://github.com/Taxel/PlexTraktSync. It looks like their documentation is more user friendly.
