### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by austinarchibald** [josh/imdb-trakt-sync#37]
Hello. I have been using your app for a little while now; always worked great. I was having issues with docker and reinstalled it, including all my containers. One was `ghcr.io/josh/imdb-trakt-sync`, but I am getting an error:

```
 ✘ imdb_trakt_sync Error Head "https://ghcr.io/v2/josh/imdb-trakt-sync/manifests/latest": denied                                     0.6s 
Error response from daemon: Head "https://ghcr.io/v2/josh/imdb-trakt-sync/manifests/latest": denied
```

Appreciate the help!

**Comment by josh** [comment]
Hi! Unfortunately I had to rewrite the entire project recently as IMDb changed how list and rating exports works. It's alot more manual now so unfortunately you can't use Docker to automatically fetch the data from IMDb anymore.
