### ISSUE TITLE
Help with Trakt Authentication

### ISSUE THREAD

**Issue by markhaines** [josh/imdb-trakt-sync#8]
Hi, I've got this container up and running and have plugged in my IMDB list details.  The script returns:

+ /app/main.sh
+ ./diff-movie-watchlist.sh
+ ./trakt-update-watchlist.sh movies
imdb-watchlist: 2154 movies
true
exit status 22

so it looks like it's grabbing my movie / tv list correctly.  I'm stuck on the trakt side though, specifically when I create a new API App i'm not sure what Redirect uri to put in and then what to use as the "TRAKT_ACCESS_TOKEN: "Authorize" the OAuth token to get a personal access token" part.  Can you help point me in the right direction?

**Comment by josh** [comment]
Half way there!

Yeah, the OAuth stuff can be a little annoying since there's no web server process. One way you can do it all on the web is using the Trakt API docs. They have an interactive API console that you can use the retrieve an API access token.

https://trakt.docs.apiary.io/#reference/authentication-oauth/authorize/authorize-application

So the `TRAKT_CLIENT_ID` is that the "Client ID" you probably already found in "Your API Apps" settings. Then the `TRAKT_ACCESS_TOKEN` is the value that gets used in every request `Authorization` header.

You can also try the "out of band" method. In that case you'd set `urn:ietf:wg:oauth:2.0:oob` as the redirect uri. That gives you a short device code you enter into the next request. This was designed for things like TVs to display and be entered in on a computer.

https://trakt.docs.apiary.io/#reference/authentication-devices/authorize-application

There's one more annoying part to all this... the access tokens expire like every 3-6 months. 😞

**Comment by markhaines** [comment]
Hey, thanks for the pointers above - I managed to get it working using the second method!  The script works perfectly, thanks so much!

**Comment by alaq** [comment]
Writing the full steps here, for myself in 3 months, or anyone finding this issue:

- Create a new app https://trakt.tv/oauth/applications/new
- Name it and set `urn:ietf:wg:oauth:2.0:oob` as the redirect uri.  Also select both permissions (I'm not sure which one is actually relevant)
- Get your client_id, and go [here](https://trakt.docs.apiary.io/#reference/authentication-devices/device-code/generate-new-device-codes), select body and replace the string here with your own client_id, send the query with "Call Resource"
- Go to https://trakt.tv/activate and use the `user_code` from the 200 response from the previous query
- Go to https://trakt.docs.apiary.io/#reference/authentication-devices/get-token/poll-for-the-access_token?console=1 and use the `device_code` from the previous query alongside the `client_id` and `client_secret` from your app to finally fetch the `access_token`

**Comment by josh** [comment]
Thanks @alaq. I’m hoping to get around to making a GUI app for this project someday. That could open a proper browser and hopefully make this process easier.

**Comment by jpbaril** [comment]
Merci/Thanks @alaq 

A little detail to make it complete. When you say to go here
https://trakt.docs.apiary.io/#reference/authentication-devices/device-code/generate-new-device-codes
We then need to either click on "Switch to Console" or "Try"

**Comment by alaq** [comment]
Merci @jpbaril, I edited my comment! I must admit I was about to give up when I thought about going to https://trakt.tv/activate 😅

**Comment by austinarchibald** [comment]
> There's one more annoying part to all this... the access tokens expire like every 3-6 months. 😞

Is there any way to automate that so we don't have to jump through those crazy hoops every 3 months?! Mine said expires in `7776000` or ~2.95 months. It's above my pay grade, but I wonder if some script could be included in the docker app to automate it, and put the new credentials in the app? If possible, it's a feature request!

And much thanks to @alaq. Would never have figured it out without those instructions!

**Comment by alaq** [comment]
@austinarchibald my pleasure!

I have to admit, my token expired in May and I haven't gotten around to updating it yet 😅

**Comment by johnaston86** [comment]
@austinarchibald 
There will be a million better ways to do this, I'm sure, but python3 auth.py is a simple as I can make it with my limited skills!

auth.py
```
import requests
import json
from requests.structures import CaseInsensitiveDict
import os
import dotenv
import sys
import fileinput

dotenv_file = dotenv.find_dotenv()
dotenv.load_dotenv(dotenv_file)

client_id = os.getenv('TRAKT_CLIENT_ID')
secret = os.getenv('TRAKT_SECRET')
client_id='"'+client_id+'"'
secret='"'+secret+'"'

url = "https://api.trakt.tv/oauth/device/code"
headers = CaseInsensitiveDict()
headers["Content-Type"] = "application/json"
data = '{"client_id":'+client_id+'}'
resp = requests.post(url, headers=headers, data=data)

data1 = json.loads(resp.content)
print("Visit "+data1['verification_url']+" and input code: "+data1['user_code'])
device_code=data1['device_code']
device_code='"'+device_code+'"'

while input("Verified? [y/n]") == "y":
    url = "https://api.trakt.tv/oauth/device/token"
    headers = CaseInsensitiveDict()
    headers["Content-Type"] = "application/json"
    data = '{"code":'+device_code+',"client_id":'+client_id+',"client_secret":'+secret+'}'
    resp = requests.post(url, headers=headers, data=data)
    data = json.loads(resp.content)
    token = data['access_token']
    dotenv.set_key(dotenv_file, 'TRAKT_ACCESS_TOKEN', token)
    print(token)

    fin = open(".env", "rt")
    data = fin.read()
    data = data.replace('"', '')
    fin.close()
    fin = open(".env", "wt")
    fin.write(data)
    fin.close()
    os.system('docker stop imdb_trakt_sync && docker rm imdb_trakt_sync && docker-compose up -d imdb_trakt_sync')
    os.system('docker logs imdb_trakt_sync')
    break
```
relies on docker-compose.yml
```
  imdb_trakt_sync:
    container_name: imdb_trakt_sync
    restart: always
    image: ghcr.io/josh/imdb-trakt-sync
    environment:
      - IMDB_UBID_MAIN=${IMDB_UBID_MAIN}
      - IMDB_AT_MAIN=${IMDB_AT_MAIN}
      - IMDB_RATINGS_ID=${IMDB_UR}
      - IMDB_WATCHLIST_ID=${IMDB_LIST}
      - TRAKT_CLIENT_ID=${TRAKT_CLIENT_ID}
      - TRAKT_ACCESS_TOKEN=${TRAKT_ACCESS_TOKEN}
      - TICKERD_INTERVAL=1h
```
and .env
```
TRAKT_CLIENT_ID=
TRAKT_SECRET=
TRAKT_ACCESS_TOKEN=
IMDB_AT_MAIN=
IMDB_UBID_MAIN=
IMDB_UR=ur
IMDB_LIST=ls
```

**Comment by rafae667** [comment]
How can I use the auth.py so I never have to update the token manually?
