### ISSUE TITLE
Can't pull image

### ISSUE THREAD

**Issue by jpbaril** [josh/imdb-trakt-sync#9]
docker pull docker.pkg.github.com/josh/imdb-trakt-sync/imdb-trakt-sync:latest
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.

docker pull  ghcr.io/josh/imdb-trakt-sync/imdb-trakt-sync:latest
Error response from daemon: Get https://ghcr.io/v2/josh/imdb-trakt-sync/imdb-trakt-sync/manifests/latest: denied

**Comment by alaq** [comment]
Do you have proper Github authentication setup, like in [this guide](https://docs.github.com/en/packages/guides/configuring-docker-for-use-with-github-packages#authenticating-with-a-personal-access-token)?

**Comment by jpbaril** [comment]
I think so.
I had also tried after using the following (adapted) command:
$ cat ~/TOKEN.txt | docker login https://docker.pkg.github.com -u USERNAME --password-stdin

Le 23 février 2021 01 h 14 min 01 s HNE, Adrien Lacquemant <notifications@github.com> a écrit :

**Comment by alaq** [comment]
Just as a sanity check, can you check that you have the “read:packages” scope for the personal access token you are using?

**Comment by josh** [comment]
Oh right I kinda forgot about GitHub Docker images needing auth. Too bad you can't fetch them anonymously. I can probably help update the docs with the GitHub api key steps. Thanks!

**Comment by jpbaril** [comment]
Well, in fact, Github is replacing docker.pkg.github.com by ghcr.io and the latter doesn't not need authentication for pulling images. So the best long term solution would be to migrate to ghcr.io.

**Comment by josh** [comment]
@jpbaril thanks, I didn’t realize they changed anything. I’ll take a look to see if anything with the GitHub Actions scripts need updating as well.

**Comment by josh** [comment]
I switched to the new container registry, but I still had to auth. Maybe public pulls won't work until they go out of beta.

```
$ docker pull ghcr.io/josh/imdb-trakt-sync/imdb-trakt-sync
Using default tag: latest
Error response from daemon: Head https://ghcr.io/v2/josh/imdb-trakt-sync/imdb-trakt-sync/manifests/latest: unauthorized
$ docker login https://ghcr.io -u josh                  
Password: 
Login Succeeded
$ docker pull ghcr.io/josh/imdb-trakt-sync/imdb-trakt-sync
Using default tag: latest
latest: Pulling from josh/imdb-trakt-sync/imdb-trakt-sync
ba3557a56b15: Pull complete 
9d48b66ea19f: Pull complete 
10a93dab72f5: Pull complete 
cb469151da63: Pull complete 
2bad2dc8fc52: Pull complete 
70e61faa67ad: Pull complete 
Digest: sha256:e58477f7b524c5a89c06f214f022d6184f074777e9970fa0e107cbeeea34fc0e
Status: Downloaded newer image for ghcr.io/josh/imdb-trakt-sync/imdb-trakt-sync:latest
ghcr.io/josh/imdb-trakt-sync/imdb-trakt-sync:latest
```
